apiVersion: v1
kind: Service
metadata:
  name: pyworld
spec:
  selector:
    app: pyworld
  ports:
  - protocol: TCP
    port: 3050
    nodePort: 30080
    targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyworld
  labels:
    app: pyworld  
spec:
  selector:
    matchLabels:
      app: pyworld
  replicas: 2
  template:
    metadata:
      labels:
        app: pyworld
    spec:
      containers:
      - name: pyworld
        image: dataexplorer/pyworld:0.0.3
        ports:
          - containerPort: 3000          